export const queryKeys = {
  currentUser: ["current-user"] as const,
  tenantDashboard: ["tenant-dashboard"] as const,
  tenantFeed: ["tenant-feed"] as const,
  tenantProperties: (filters: unknown) => ["tenant-properties", filters] as const,
  tenantProperty: (propertyId: string) => ["tenant-property", propertyId] as const,
  tenantFavourites: ["tenant-favourites"] as const,
  tenantEnquiries: (status: string) => ["tenant-enquiries", status] as const,
  tenantEnquiry: (enquiryId: string) => ["tenant-enquiry", enquiryId] as const,
  tenantProfile: ["tenant-profile"] as const,
  landlordDashboard: ["landlord-dashboard"] as const,
  landlordProfile: ["landlord-profile"] as const,
  landlordVerification: ["landlord-verification"] as const,
  landlordProperties: (status: string) => ["landlord-properties", status] as const,
  landlordProperty: (propertyId: string) => ["landlord-property", propertyId] as const,
  landlordEnquiries: ["landlord-enquiries"] as const,
  superAdminDashboard: ["super-admin-dashboard"] as const,
};
