export const queryKeys = {
  currentUser: ["current-user"] as const,
  notifications: ["notifications"] as const,
  notificationPreferences: ["notification-preferences"] as const,
  tenantDashboard: ["tenant-dashboard"] as const,
  tenantFeed: (filters?: unknown) => ["tenant-feed", filters ?? {}] as const,
  tenantProperties: (filters: unknown) => ["tenant-properties", filters] as const,
  tenantProperty: (propertyId: string) => ["tenant-property", propertyId] as const,
  tenantFavourites: ["tenant-favourites"] as const,
  tenantEnquiries: (status: string) => ["tenant-enquiries", status] as const,
  tenantEnquiry: (enquiryId: string) => ["tenant-enquiry", enquiryId] as const,
  tenantProfile: ["tenant-profile"] as const,
  landlordDashboard: ["landlord-dashboard"] as const,
  landlordProfile: ["landlord-profile"] as const,
  landlordVerification: ["landlord-verification"] as const,
  landlordProperties: (status: string) => ["landlord-properties", status] as const,
  landlordProperty: (propertyId: string) => ["landlord-property", propertyId] as const,
  landlordEnquiries: ["landlord-enquiries"] as const,
  landlordEnquiry: (enquiryId: string) => ["landlord-enquiry", enquiryId] as const,
  ghanaLocations: ["ghana-locations"] as const,
  superAdminDashboard: ["super-admin-dashboard"] as const,
  superAdminApprovals: (filters: unknown) => ["super-admin-approvals", filters] as const,
  superAdminProperty: (propertyId: string) => ["super-admin-property", propertyId] as const,
  superAdminLandlordVerifications: (filters: unknown) => ["super-admin-landlord-verifications", filters] as const,
  superAdminLandlordVerification: (profileId: string) => ["super-admin-landlord-verification", profileId] as const,
  superAdminReports: (filters: unknown) => ["super-admin-reports", filters] as const,
  superAdminUsers: (filters: unknown) => ["super-admin-users", filters] as const,
  superAdminNotifications: (filters: unknown) => ["super-admin-notifications", filters] as const,
};
