import { and, eq, inArray } from "drizzle-orm";
import { z } from "zod";
import { db } from "@/db";
import { properties, propertyReports } from "@/db/schema";
import { guardErrorResponse, requireTenant } from "@/lib/auth-guards.server";
import { errorResponse, internalServerErrorResponse, notFoundResponse, successResponse, validationErrorResponse } from "@/lib/api-response";
import { notifySuperAdmins } from "@/lib/notifications/dispatcher.server";
const schema = z.object({ propertyId: z.string().min(1), reason: z.enum(["SCAM", "MISLEADING", "UNAVAILABLE", "DUPLICATE", "OTHER"]), description: z.string().trim().max(1000).optional() });
export async function POST(request: Request) { try { const context = await requireTenant(request); const parsed = schema.safeParse(await request.json()); if (!parsed.success) return validationErrorResponse(parsed.error); const property = await db.query.properties.findFirst({ where: eq(properties.id, parsed.data.propertyId) }); if (!property) return notFoundResponse("Property not found."); const duplicate = await db.query.propertyReports.findFirst({ where: and(eq(propertyReports.propertyId, property.id), eq(propertyReports.reporterId, context.user.id), inArray(propertyReports.status, ["OPEN", "REVIEWING"])) }); if (duplicate) return errorResponse("REPORT_ALREADY_OPEN", "You already have an open report for this property.", 409); const id = crypto.randomUUID(); await db.insert(propertyReports).values({ id, propertyId: property.id, reporterId: context.user.id, reason: parsed.data.reason, description: parsed.data.description }); await notifySuperAdmins({ type: "PROPERTY_REPORT", category: "REPORT", eventKey: "report.created", priority: "HIGH", title: "New property report", message: `${context.user.name} reported ${property.title}.`, deepLink: "/super-admin/reports", relatedEntityType: "property_report", relatedEntityId: id, deduplicationKey: `report-created:${id}` }); return successResponse({ reportId: id }, { status: 201, message: "Report submitted." }); } catch(error) { try{return guardErrorResponse(error)}catch(e){console.error("POST /api/tenant/reports failed", e); return internalServerErrorResponse()} } }
